In [538]:
# Importer les libraries
import pandas as pd
import numpy as np
import unidecode
import warnings
from datetime import datetime
warnings.filterwarnings('ignore')

In [539]:
# Importer le dataset
df = pd.read_csv('openaq.csv',delimiter = ';', encoding = 'utf-8')

In [540]:
# Apercu du dataset
df

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,CN,盘锦市,兴隆台,"41.0883,122.0485",O3,ChinaAQIData,µg/m³,180.0,2021-08-09T13:00:00+02:00,China
1,CN,郴州市,兴隆步行街,"25.8001,113.0161",CO,ChinaAQIData,µg/m³,600.0,2021-08-09T13:00:00+02:00,China
2,CN,长春市,净月潭,"43.79,125.4605",SO2,ChinaAQIData,µg/m³,4.0,2021-08-09T13:00:00+02:00,China
3,CN,上饶市,凤凰光学,"28.4628,117.9519",PM2.5,ChinaAQIData,µg/m³,29.0,2021-08-09T13:00:00+02:00,China
4,CN,南宁市,北湖,"22.8528,108.3141",CO,ChinaAQIData,µg/m³,600.0,2021-08-09T13:00:00+02:00,China
...,...,...,...,...,...,...,...,...,...,...
46643,GB,Cardiff,Cardiff Centre,"51.48178,-3.17625",SO2,DEFRA,µg/m³,6.0,2022-07-25T07:00:00+02:00,United Kingdom
46644,GB,Cardiff,Cardiff Centre,"51.48178,-3.17625",O3,DEFRA,µg/m³,42.0,2022-07-25T07:00:00+02:00,United Kingdom
46645,GB,Plymouth,Plymouth Centre,"50.37167,-4.142361",PM10,DEFRA,µg/m³,19.0,2022-07-25T07:00:00+02:00,United Kingdom
46646,GB,Hull,Hull Freetown,"53.74878,-0.341222",O3,DEFRA,µg/m³,25.0,2022-07-25T07:00:00+02:00,United Kingdom
46647,GB,Leicester,Leicester University,"52.619823,-1.127311",PM2.5,DEFRA,µg/m³,4.0,2022-07-25T07:00:00+02:00,United Kingdom

In [541]:
# Nombres de lignes et de colonnes
df.shape

(46648, 10)

#### 1.- Supprimer les données qui ne concernent pas la journée du 06-08-2021.

In [542]:
df['Last Updated'] = df['Last Updated'].str[0:10]

In [543]:
df.head()

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,CN,盘锦市,兴隆台,"41.0883,122.0485",O3,ChinaAQIData,µg/m³,180.0,2021-08-09,China
1,CN,郴州市,兴隆步行街,"25.8001,113.0161",CO,ChinaAQIData,µg/m³,600.0,2021-08-09,China
2,CN,长春市,净月潭,"43.79,125.4605",SO2,ChinaAQIData,µg/m³,4.0,2021-08-09,China
3,CN,上饶市,凤凰光学,"28.4628,117.9519",PM2.5,ChinaAQIData,µg/m³,29.0,2021-08-09,China
4,CN,南宁市,北湖,"22.8528,108.3141",CO,ChinaAQIData,µg/m³,600.0,2021-08-09,China

In [544]:
df['Last Updated'] = df['Last Updated'].astype('datetime64[ns]')

In [545]:
df['Last Updated'] = pd.to_datetime(df['Last Updated'],format='%d-%m-%Y', errors='coerce')

#### 2.- Supprimer les données qui sont illisibles et pour lesquelles on ne comprend pas la ville concernée.

In [546]:
df['City'] = df['City'].str.replace(r'[^\x00-\x7F]+', '') # Remplacer les caractères chinois

In [547]:
df['Location'] = df['Location'].str.replace(r'[^\x00-\x7F]+', '')# Remplacer les caractères chinois

In [548]:
df.head()

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,CN,,,"41.0883,122.0485",O3,ChinaAQIData,µg/m³,180.0,2021-08-09,China
1,CN,,,"25.8001,113.0161",CO,ChinaAQIData,µg/m³,600.0,2021-08-09,China
2,CN,,,"43.79,125.4605",SO2,ChinaAQIData,µg/m³,4.0,2021-08-09,China
3,CN,,,"28.4628,117.9519",PM2.5,ChinaAQIData,µg/m³,29.0,2021-08-09,China
4,CN,,,"22.8528,108.3141",CO,ChinaAQIData,µg/m³,600.0,2021-08-09,China

In [549]:
df['City'].replace('', np.nan, inplace=True)

In [550]:
df['Location'].replace('', np.nan, inplace=True)

In [551]:
dataset = df.dropna()

In [552]:
dataset

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
288,CN,Suzhou,Suzhou Jian Ce Lou,"33.6481,116.9765",PM10,Suzhou,µg/m³,152.000,2018-12-04,China
294,DE,Berlin,DEBE068,"52.513606,13.418833",PM2.5,EEA Germany,µg/m³,8.670,2022-07-22,Germany
295,DE,Bayern,DEBY187,"48.95218,10.59772",NO2,EEA Germany,µg/m³,10.540,2022-07-22,Germany
296,DE,Bayern,DEBY001,"49.304889,10.572297",NO2,EEA Germany,µg/m³,16.710,2022-07-22,Germany
297,DE,Schleswig-Holstein,DESH055,"53.87453,10.664881",NO2,EEA Germany,µg/m³,7.171,2022-07-22,Germany
...,...,...,...,...,...,...,...,...,...,...
46643,GB,Cardiff,Cardiff Centre,"51.48178,-3.17625",SO2,DEFRA,µg/m³,6.000,2022-07-25,United Kingdom
46644,GB,Cardiff,Cardiff Centre,"51.48178,-3.17625",O3,DEFRA,µg/m³,42.000,2022-07-25,United Kingdom
46645,GB,Plymouth,Plymouth Centre,"50.37167,-4.142361",PM10,DEFRA,µg/m³,19.000,2022-07-25,United Kingdom
46646,GB,Hull,Hull Freetown,"53.74878,-0.341222",O3,DEFRA,µg/m³,25.000,2022-07-25,United Kingdom
46647,GB,Leicester,Leicester University,"52.619823,-1.127311",PM2.5,DEFRA,µg/m³,4.000,2022-07-25,United Kingdom

#### 3.-Pour chaque polluant, vérifier qu'on n'a qu'une seule mesure utilisée. Autrement, supprimer les données qui correspondent à la mesure minoritaire ou moins cohérente.

In [553]:
df.Unit.value_counts()

µg/m³    38420
ppm       8228
Name: Unit, dtype: int64

#### 4.- Regarder s'il y a des valeurs aberrantes ou des problèmes par rapport à notre objectif final (pouvoir comparer des mesures sur un maximum de pays) et noter ces aspects dans un fichier texte.